### ISSUE TITLE
Real-time working

### ISSUE THREAD

**Issue by MShia** [Max-Manning/passiveRadar#3]
It seems the code is optimized for offline processing, specially the calculation of offset and other processing takes a lot of time.What changes should we make to run this in real-time.

**Comment by Max-Manning** [comment]
Thanks for the question! I've actually given this some thought but haven't gotten around to trying to implement it yet.

The easiest way to get real-time performance would probably be to translate the main processing steps (channel offset correction, clutter removal and range-doppler processing) into [gnuradio](https://github.com/gnuradio/gnuradio) blocks so that the processing could be implemented as a flow graph. Implementing the heavy parts in C++ instead of python could increase throughput. Also, the range-doppler processing step involves doing many identical calculations (a FFT along the doppler axis for each range bin) which are currently just done sequentially in a for loop - this would be a pretty good target for parallelization (either CPU or GPU).

Another (more difficult) approach would be to offload the heavy processing to a fpga on a SDR platform that has one (eg Ettus USRP or Nuand BladeRF).
